Cara 1

In [1]:
from numpy import*
# Inisialisasi Matriks
A = array([[1.,1.,0.,3.,4],
           [2.,1.,-1.,1.,1],
           [3.,-1.,-1.,2.,-3],
           [-1.,2.,3.,-1,4]])
print ("Matriks A=",A)

n=len(A)
# Trianglurasisasi
for k in range(0,n-1):
    for i in range(k+1,n):
        m=A[i][k]/A[k][k]
        for j in range(0,n+1):
            A[i][j]=A[i][j]-m*A[k][j]

# Subtitusi Mundur
X = zeros((n,1))
X[n-1][0]=A[n-1][n]/A[n-1][n-1]
for j in range(n-2,-1,-1):
    S=0
    for i in range(j+1,n):
        S=S+A[j][i]*X[i][0]
        X[j][0]=(A[j][n]-S)/A[j][j]

print ("X=",X)

Matriks A= [[ 1.  1.  0.  3.  4.]
 [ 2.  1. -1.  1.  1.]
 [ 3. -1. -1.  2. -3.]
 [-1.  2.  3. -1.  4.]]
X= [[-1.]
 [ 2.]
 [ 0.]
 [ 1.]]


Cara 2

In [3]:
# Library
import numpy as np
# Matriks A dan B
A = np.array([[1, 1, -1],
              [1, 2, 1],
              [2, 1, 1]], float)
B = np.array([[-3],
              [7],
              [4]], float)
# Stack Matriks Secara horizontal
AB = np.hstack([A, B])
print(AB)

# Eliminasi Gauss
n = len(B)
for p in range(0, n-1):
  for q in range(p+1, n):
    lam= AB[p,p] / AB[q,p]
    AB[q] = AB[p] - lam * AB[q]
print("\nEliminasi Gauss:\n", AB)

# Subtitusi
for p in range(n-1, -1, -1):
  AB[p] = AB[p] / AB[p,p]
  for q in range(p - 1, -1, -1):
    lam = AB[p, p] / AB[q, p]
    AB[q] = AB[p] - lam * AB[q]
print("\nSubtitusi:\n", AB)

# Hasil
hasil = AB[:, 3]
print("\nHasil:\n[X, Y, Z] =", hasil)

[[ 1.  1. -1. -3.]
 [ 1.  2.  1.  7.]
 [ 2.  1.  1.  4.]]

Eliminasi Gauss:
 [[  1.   1.  -1.  -3.]
 [  0.  -1.  -2. -10.]
 [  0.   0.  -5. -20.]]

Subtitusi:
 [[ 1. -0.  0. -1.]
 [-0.  1. -0.  2.]
 [-0. -0.  1.  4.]]

Hasil:
[X, Y, Z] = [-1.  2.  4.]
