In [1]:
import numpy as np
A = np.array([[1, 1, -1],
              [1, 2, 1],
              [2, 1, 1]], float)
B = np.array([[-3],
              [7],
              [4]], float)
AB = np.hstack([A, B])
print(AB)

n = len(B)
for p in range(0, n-1):
  for q in range(p+1, n):
    lam= AB[p,p] / AB[q,p]
    AB[q] = AB[p] - lam * AB[q]
print("\nEliminasi Gauss:\n", AB)

for p in range(n-1, -1, -1):
  AB[p] = AB[p] / AB[p,p]
  for q in range(p - 1, -1, -1):
    lam = AB[p, p] / AB[q, p]
    AB[q] = AB[p] - lam * AB[q]
print("\nSubtitusi:\n", AB)

hasil = AB[:, 3]
print("\nHasil:\n[X, Y, Z] =", hasil)

[[ 1.  1. -1. -3.]
 [ 1.  2.  1.  7.]
 [ 2.  1.  1.  4.]]

Eliminasi Gauss:
 [[  1.   1.  -1.  -3.]
 [  0.  -1.  -2. -10.]
 [  0.   0.  -5. -20.]]

Subtitusi:
 [[ 1. -0.  0. -1.]
 [-0.  1. -0.  2.]
 [-0. -0.  1.  4.]]

Hasil:
[X, Y, Z] = [-1.  2.  4.]
