## Definisi Fungsi Dekomposisi LU

In [1]:
def decomposition(A):
  # mendapatkan jumlah baris matriks A
  n = len(A)

  # Membuat matriks kosong dari L dan U
  L = [[0 for row in range(n)]
       for col in range(n)]
  U = [[0 for row in range(n)]
       for col in range(n)]
  
  for p in range(n):
    # upper matriks
    for j in range(p,n):
      # penjumlahan dari L(p,k)*U(k,j)
      sum = 0
      for k in range(p):
        sum = sum + L[p][k]*U[k][j]
      U[p][j] = A[p][j] - sum

    # lower matriks
    q = p
    for i in range (q,n):
      if (i==q):
        # diagonal dari L
        L[i][q]=1
      else:
        # penjumlahan dari L(i,k)*U(k,q)
        sum = 0
        for k in range(q):
          sum = sum + L[i][k]*U[k][q]
        L[i][q] = (A[i][q] - sum)/U[q][q]

  return L, U

## Menentukan Fungsi untuk Menampilkan Elemen Matriks

In [2]:
def show(matrix):
  n = len(matrix)
  for row in range(n):
    for col in range(n):
      print('%.2f' % matrix[row][col], end="\t")
    print("")

## Menghitung Matrix L and U

In [3]:
# matrix A
A = [[3, 2, -1],
     [2, -2, 4],
     [-1, 3, -1]]

# menghitung L and U     
L, U = decomposition(A)

# nemapilkan L and U
print("Matrix L :")
show(L)

print("\nMatrix U :")
show(U)

Matrix L :
1.00	0.00	0.00	
0.67	1.00	0.00	
-0.33	-1.10	1.00	

Matrix U :
3.00	2.00	-1.00	
0.00	-3.33	4.67	
0.00	0.00	3.80	


## A = LU

In [4]:
import numpy as np

print("A:")
show(A)

LU = np.dot(L,U)
print("\nL.U:")
show(LU)

A:
3.00	2.00	-1.00	
2.00	-2.00	4.00	
-1.00	3.00	-1.00	

L.U:
3.00	2.00	-1.00	
2.00	-2.00	4.00	
-1.00	3.00	-1.00	


##Cara 2

In [4]:
import numpy as np
import scipy.linalg as lg

A = np.array([[3, 2, -1],
              [2, -2, 4],
              [-1, 3, -1]])

print ("A: ")
print (A)
print("\n")

P, L, U = lg.lu(A)
print ("L: ")
print (L)
print("\n")

print ("U: ")
print (U)

A: 
[[ 3  2 -1]
 [ 2 -2  4]
 [-1  3 -1]]


L: 
[[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [ 0.66666667 -0.90909091  1.        ]]


U: 
[[ 3.          2.         -1.        ]
 [ 0.          3.66666667 -1.33333333]
 [ 0.          0.          3.45454545]]
