# SPL
<hr>


## 1. Dekomposisi LU

Cara 1.



In [4]:
# Dekomposisi
def decomposition(A):
  # mendapatkan jumlah baris matriks A
  n = len(A)

  # Membuat matriks kosong dari L dan U
  L = [[0 for row in range(n)]
       for col in range(n)]
  U = [[0 for row in range(n)]
       for col in range(n)]
  
  for p in range(n):
    # upper matriks
    for j in range(p,n):
      # penjumlahan dari L(p,k)*U(k,j)
      sum = 0
      for k in range(p):
        sum = sum + L[p][k]*U[k][j]
      U[p][j] = A[p][j] - sum

    # lower matriks
    q = p
    for i in range (q,n):
      if (i==q):
        # diagonal dari L
        L[i][q]=1
      else:
        # penjumlahan dari L(i,k)*U(k,q)
        sum = 0
        for k in range(q):
          sum = sum + L[i][k]*U[k][q]
        L[i][q] = (A[i][q] - sum)/U[q][q]

  return L, U

# Tampilkan Matriks
def show(matrix):
  n = len(matrix)
  for row in range(n):
    for col in range(n):
      print('%.2f' % matrix[row][col], end="\t")
    print("")

# Menghitung Matriks L dan U
A = [[3, 2, -1],
     [2, -2, 4],
     [-1, 3, -1]]

# menghitung L and U     
L, U = decomposition(A)

# nemapilkan L and U
print("Matrix L :")
show(L)

print("\nMatrix U :")
show(U)

# A = LU
print("A:")
show(A)

LU = np.dot(L,U)
print("\nL.U:")
show(LU)

Matrix L :
1.00	0.00	0.00	
0.67	1.00	0.00	
-0.33	-1.10	1.00	

Matrix U :
3.00	2.00	-1.00	
0.00	-3.33	4.67	
0.00	0.00	3.80	
A:
3.00	2.00	-1.00	
2.00	-2.00	4.00	
-1.00	3.00	-1.00	

L.U:
3.00	2.00	-1.00	
2.00	-2.00	4.00	
-1.00	3.00	-1.00	


Cara 2

In [1]:
import numpy as np
import scipy.linalg as lg

A = np.array([[3, 2, -1],
              [2, -2, 4],
              [-1, 3, -1]])

print ("A: ")
print (A)
print("\n")

P, L, U = lg.lu(A)
print ("L: ")
print (L)
print("\n")

print ("U: ")
print (U)

A: 
[[ 3  2 -1]
 [ 2 -2  4]
 [-1  3 -1]]


L: 
[[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [ 0.66666667 -0.90909091  1.        ]]


U: 
[[ 3.          2.         -1.        ]
 [ 0.          3.66666667 -1.33333333]
 [ 0.          0.          3.45454545]]


## 2. Doolitle

In [5]:
# Batas maksimal upper dan lower matriks
MAX = 100


def luDecomposition(mat, n):
    lower = [[0 for x in range(n)]
             for y in range(n)]
    upper = [[0 for x in range(n)]
             for y in range(n)]

    # Dekomposisi matriks  Upper dan Lower ke dalam triangular matrix
    for i in range(n):

        # Upper
        for k in range(i, n):

            # Summation of L(i, j) * U(j, k)
            sum = 0
            for j in range(i):
                sum += (lower[i][j] * upper[j][k])

            # Evaluating U(i, k)
            upper[i][k] = mat[i][k] - sum

        # Lower
        for k in range(i, n):
            if (i == k):
                lower[i][i] = 1  # Diagonal as 1
            else:

                # Summation of L(k, j) * U(j, i)
                sum = 0
                for j in range(i):
                    sum += (lower[k][j] * upper[j][i])

                # Evaluating L(k, i)
                lower[k][i] = int((mat[k][i] - sum) /
                                  upper[i][i])

    # Tampilan upper dan lower
    print("Lower Triangular\t\tUpper Triangular")

    # Tampilan hasil
    for i in range(n):

        # Lower
        for j in range(n):
            print(lower[i][j], end="\t")
        print("", end="\t")

        # Upper
        for j in range(n):
            print(upper[i][j], end="\t")
        print("")


# Matriks yang digunakan
mat = [[2, -1, -2],
       [-4, 6, 3],
       [-4, -2, 8]]

luDecomposition(mat, 3)

Lower Triangular		Upper Triangular
1	0	0		2	-1	-2	
-2	1	0		0	4	-1	
-2	-1	1		0	0	3	


## 3. Gauss

In [6]:
from numpy import*
# Inisialisasi Matriks
A = array([[1.,1.,0.,3.,4],
           [2.,1.,-1.,1.,1],
           [3.,-1.,-1.,2.,-3],
           [-1.,2.,3.,-1,4]])
print ("Matriks A=",A)

n=len(A)
# Trianglurasisasi
for k in range(0,n-1):
    for i in range(k+1,n):
        m=A[i][k]/A[k][k]
        for j in range(0,n+1):
            A[i][j]=A[i][j]-m*A[k][j]

# Subtitusi Mundur
X = zeros((n,1))
X[n-1][0]=A[n-1][n]/A[n-1][n-1]
for j in range(n-2,-1,-1):
    S=0
    for i in range(j+1,n):
        S=S+A[j][i]*X[i][0]
        X[j][0]=(A[j][n]-S)/A[j][j]

print ("X=",X)

Matriks A= [[ 1.  1.  0.  3.  4.]
 [ 2.  1. -1.  1.  1.]
 [ 3. -1. -1.  2. -3.]
 [-1.  2.  3. -1.  4.]]
X= [[-1.]
 [ 2.]
 [ 0.]
 [ 1.]]


Gauss Cara 2

In [8]:
# Library
import numpy as np
# Matriks A dan B
A = np.array([[1, 1, -1],
              [1, 2, 1],
              [2, 1, 1]], float)
B = np.array([[-3],
              [7],
              [4]], float)
# Stack Matriks Secara horizontal
AB = np.hstack([A, B])
print(AB)

# Eliminasi Gauss
n = len(B)
for p in range(0, n-1):
  for q in range(p+1, n):
    lam= AB[p,p] / AB[q,p]
    AB[q] = AB[p] - lam * AB[q]
print("\nEliminasi Gauss:\n", AB)

# Subtitusi
for p in range(n-1, -1, -1):
  AB[p] = AB[p] / AB[p,p]
  for q in range(p - 1, -1, -1):
    lam = AB[p, p] / AB[q, p]
    AB[q] = AB[p] - lam * AB[q]
print("\nSubtitusi:\n", AB)

# Hasil
hasil = AB[:, 3]
print("\nHasil:\n[X, Y, Z] =", hasil)

[[ 1.  1. -1. -3.]
 [ 1.  2.  1.  7.]
 [ 2.  1.  1.  4.]]

Eliminasi Gauss:
 [[  1.   1.  -1.  -3.]
 [  0.  -1.  -2. -10.]
 [  0.   0.  -5. -20.]]

Subtitusi:
 [[ 1. -0.  0. -1.]
 [-0.  1. -0.  2.]
 [-0. -0.  1.  4.]]

Hasil:
[X, Y, Z] = [-1.  2.  4.]
